### ISSUE TITLE
Fix UI: Header and color pallet

### ISSUE THREAD

**Issue by Tarandeep-s1ngh** [varunherlekar/lets-do-it#16]
Hi @varunherlekar  , Amazing project brother! I am into UI and styling, would like to fix the following issues:
1) Fix: Header is currently taking 1/3rd of the entire screen, which leads to cluttering of main content i.e. ToDo List. I will snug fit the header so that it takes space according to the content inside it. This will give more breathing space to ToDo List
2) Style: Current color pallet of the header and footer is not going hand-in-hand with each other. Would like to work on this also.

Please assign this to me, and this would be my first PR merge ever!

**Comment by varunherlekar** [comment]
@all-contributors please add @Tarandeep-s1ngh for design

**Comment by varunherlekar** [comment]
@all-contributors please add @Tarandeep-s1ngh for design
