### ISSUE TITLE
Feature to restore the completed task.

### ISSUE THREAD

**Issue by varunherlekar** [varunherlekar/lets-do-it#17]

**Comment by ankitgauri26** [comment]
@varunherlekar  - Can i work on this? Can you give more details?
Thanks in advance

**Comment by ankitgauri26** [comment]
@varunherlekar - Thank you for assigning this issue to me.
My understanding is, if the user has marked the issue as "complete" and the issue moves to complete list. We need to add a button in complete task list say "undone". After clicking on the "undone" button, it will again more from complete list to task list. Please correct me if my understanding is not correct.

**Comment by varunherlekar** [comment]
Yes correct.

**Comment by ankitgauri26** [comment]
@varunherlekar - Thank you the clarification. I'll work on this now.
