### ISSUE TITLE
Improve UI: Footer

### ISSUE THREAD

**Issue by icoderharshit** [varunherlekar/lets-do-it#2]
Hey @varunherlekar , this is actually a great project and you have maintained a nice repository. I want to contribute to this project by improving the UI of the website a bit. For now, I want to improve the footer design and placement on the page. I am a Graphics Designer by passion, so kindly assign me this issue so that I can get my first PR for Hacktoberfest '21 merged.

**Comment by varunherlekar** [comment]
Please go ahead 👍

**Comment by kapilbhale** [comment]
@varunherlekar Please can you assign this task. I would like to work on it.

**Comment by varunherlekar** [comment]
Hey @kapilbhale this issue has already been resolved.

**Comment by kapilbhale** [comment]
@varunherlekar Is there any other issue ?

**Comment by varunherlekar** [comment]
@kapilbhale you can create one.
