### ISSUE TITLE
Improve User Interface

### ISSUE THREAD

**Issue by NitinNair89** [varunherlekar/lets-do-it#21]
Hi @varunherlekar 

I think the overall user interface can be improved. Do you have any plans for redesign?

Also, do we need the APIs for displaying quotes and wallpapers? We can instead have one static fixed background as a wallpaper and work on the overall theme of the web app.

Let me know your thoughts, and we can work together on this. 🙂

**Comment by varunherlekar** [comment]
Yes, Sure we can work on it.

**Comment by varunherlekar** [comment]
Can I assign this to you ?

**Comment by NitinNair89** [comment]
> Can I assign this to you ?

Sure, please assign. 👍🏻

**Comment by NitinNair89** [comment]
Hi @varunherlekar Are you okay with removing quotes and Unsplash API integration?

**Comment by varunherlekar** [comment]
Yes

**Comment by NitinNair89** [comment]
Hi @varunherlekar I have created PR to fix this issue. Please review and let me know if any suggestions/changes.
