### ISSUE TITLE
Improve user experience

### ISSUE THREAD

**Issue by gauri242** [varunherlekar/lets-do-it#22]
Hi @varunherlekar I am a QA Tester and while testing your project I found some user experience issue as below : 
While editing the task it should show 'Save' button instead of 'Edit'.

"Note: If you don't mind, please allow me to open more issues and report bugs so that we can work together on improving this project."

<img width="963" alt="Save button" src="https://user-images.githubusercontent.com/56014138/135725394-d19beb6a-5cb9-401a-a722-93d56c678dab.png">

**Comment by varunherlekar** [comment]
Yes, you can open more issues.

**Comment by varunherlekar** [comment]
Can I assign this task to you ?

**Comment by gauri242** [comment]
> Can I assign this task to you ?

Yes
