### ISSUE TITLE
Option to remove the task once it has been marked completed

### ISSUE THREAD

**Issue by loud-mouth** [varunherlekar/lets-do-it#27]
Hi @varunherlekar, while using the webapp, I noticed that once tasks have been completed, they can no longer be removed from the 'completed tasks' section. I think if a feature was implemented to clear the completed list, this app could be used over and over for different sets of tasks by the same user without cluttering the completed tasks section.

 I'd like to implement this. Thanks.

**Comment by varunherlekar** [comment]
Yeah Sure. Assigning it to you.
