### ISSUE TITLE
Add task button not working.

### ISSUE THREAD

**Issue by varunherlekar** [varunherlekar/lets-do-it#47]

**Comment by SHRIYA-GLITCH** [comment]
Kindly describe a bit.

**Comment by varunherlekar** [comment]
Please check https://varunherlekar.github.io/lets-do-it

**Comment by SHRIYA-GLITCH** [comment]
I would like to give it a try.

**Comment by varunherlekar** [comment]
Yeah sure

**Comment by rishuverma** [comment]
what is the issue exactly, I checked the app and the "Add task" button seems working?

**Comment by SHRIYA-GLITCH** [comment]
> Please check https://varunherlekar.github.io/lets-do-it

I think ADD TASK BUTTON is just working fine.
