### ISSUE TITLE
Edit Task Button Not Working.

### ISSUE THREAD

**Issue by varunherlekar** [varunherlekar/lets-do-it#9]

**Comment by varunherlekar** [comment]
Hey @ankitgauri26 Please check if you can work on this issue as well.

**Comment by ankitgauri26** [comment]
@varunherlekar  - Sure. Can you please assign it me?

**Comment by ankitgauri26** [comment]
@varunherlekar  - I have started working on the same. Please assign the issue to me when you are available

**Comment by ankitgauri26** [comment]
@varunherlekar - I have raised PR for Edit task functionality.

**Comment by ankitgauri26** [comment]
@varunherlekar  - Thank you so much for adding me in the contributors list. I really appreciate :).
